.gitignore, CHANGELOG.md, builder/vmware/iso/step_create_vmx.go, builder/vmware/iso/step_create_vmx_test.go, example/build.pkr.hcl, example/http/preseed.cfg
The main change is being imported from https://github.com/hashicorp/packer/pull/10862
Closes https://github.com/hashicorp/packer-plugin-vmware/issues/16
=> Make hpet default to true

docs/builders/index.mdx
Description:
```bash
Adds context for the configuration of the Packer Plugin in Packer >= v1.7.0.
```
=> Add Packer configuration context

.github/CONTRIBUTING.md
Updates the `CONTRIBUTING.md` to spell "VMware" correctly.
Signed-off-by: Ryan Johnson <johnsonryan@vmware.com>
=> docs: update `CONTRIBUTING.md`

builder/vmware/common/driver.go, builder/vmware/common/driver_esx5_test.go, builder/vmware/common/driver_mock.go, builder/vmware/common/driver_parser.go, builder/vmware/common/step_clean_files.go, builder/vmware/common/step_clean_vmx.go, builder/vmware/common/step_compact_disk.go, builder/vmware/common/step_configure_vmx.go, builder/vmware/common/step_configure_vnc.go, builder/vmware/common/step_create_disks.go, builder/vmware/common/step_create_snapshot.go, builder/vmware/common/step_run.go, builder/vmware/common/step_shutdown.go, builder/vmware/common/step_upload_vmx.go, builder/vmware/common/step_vnc_boot_command.go, builder/vmware/iso/step_create_vmx.go, go.mod, go.sum
- Fix go mod tidy check errors
- Resolve spacing issues to fix goimport errors
=> Fix issues reported by Go checks

docs/builders/index.mdx
Resubmitting #39 under my personal account so I can sign the CLA.
=> docs: Add instructions for VMware Player on Linux

version/version.go
- version: cut release 1.0.11
- version: prepare for 1.0.12 dev
=> Cut release 1.0.11

.gitignore, builder/vmware/common/step_export_test.go
Updates `.gitignore` and test output directories.
=> chore: update `.gitignore`

.github/ISSUE_TEMPLATE/config.yml
Adds the `config.yml` for issues to show contact links to the following alongside the options for bugs, enhancements, questions, etc.
The results will look like the following:
=> chore: add issues `config.yml`

.web-docs/README.md, README.md, docs/README.md
Updates `./README.md` and `./docs/README.md`
**Note**: This includes the references to the deprecation of support for both the VMware vSphere Hypervisor (ESXi) and VMware Workstation Player that @nywilken and I have discussed recently and is noted in the changes here.
=> docs: update `README.md`

builder/vmware/common/step_register.go
- Moves the destroy timeout value to a constant.
- Avoids logging an error before checking if it exists.
- Combines the timeout error message logging and UI notification: Since both actions occur together, keep them within the same conditional block to avoid repetition.
- Uses a ticker for periodic checks instead of manually sleeping and checking. This is more idiomatic and readable.
Standard
```console
packer-plugin-vmware on  refactor/register
➜ go fmt ./...                                 
packer-plugin-vmware on  refactor/register
2024/07/08 14:10:42 Copying "docs" to ".docs/"
2024/07/08 14:10:42 Replacing @include '...' calls in .docs/
packer-plugin-vmware on  refactor/register
➜ make build …
```
=> refactor: register virtual machine

.web-docs/components/builder/iso/README.md, .web-docs/components/builder/vmx/README.md, builder/vmware/common/driver_config.go, builder/vmware/iso/config.hcl2spec.go, builder/vmware/vmx/config.hcl2spec.go, docs-partials/builder/vmware/Footnotes.mdx, docs-partials/builder/vmware/RemoteHypervisorBuilds.mdx, docs-partials/builder/vmware/SshKeyPairAutomation.mdx, docs-partials/builder/vmware/VncPortDiscovery.mdx, docs-partials/builder/vmware/common/DriverConfig-not-required.mdx, docs/builders/iso.mdx, docs/builders/vmx.mdx
Updates the layout of the documentation:
- Readability.
- HCL-first, where applicable.
- Topic hevels and headers (required vs optional).
- Remove duplications.
=> docs: update layouts

builder/vmware/common/driver_parser.go
Updates the following in `driver_parser.go`
- `hardware` - length of the octets and ensure address is 6 bytes.
- `subnet` - ensure within the 0-255 range instead of parsing a value larger than 255.
```shell
packer-plugin-vmware on  chore/address-parsing [$] via 🐹 v1.23.0 
➜ go fmt ./...                             
packer-plugin-vmware on  chore/address-parsing [$] via 🐹 v1.23.0 
➜ go build    
packer-plugin-vmware on  chore/address-parsing [$] via 🐹 v1.23.0 took 5.0s 
➜ make test
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/common 7.202s
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/iso    3.007s …
```
=> chore: address parsing

builder/vmware/iso/config.go
Resolves the duplicate import of `github.com/hashicorp/packer-plugin-sdk/packer`.
=> fix: duplicate import

builder/vmware/common/driver_workstation10_windows.go, builder/vmware/common/driver_workstation9.go, builder/vmware/common/driver_workstation9_windows.go, builder/vmware/common/ssh.go, builder/vmware/common/step_clean_vmx.go, builder/vmware/common/step_configure_vmx.go, builder/vmware/common/step_configure_vnc.go, builder/vmware/common/step_http_ip_discover.go, builder/vmware/common/step_register.go, builder/vmware/common/step_remote_upload.go, builder/vmware/common/step_suppress_messages.go, builder/vmware/common/vmx.go
Technical Debt: Updates log messages based on `INFO` or `WARN` context.
=> chore: update log messages

builder/vmware/common/driver_fusion.go
Includes updates to the `builder/vmware/common/driver_fusion.go` file to improve logging messages and code comments. The most important changes include adding a comment header for VMware Fusion, modifying a log message for clarity, and removing an outdated comment.
=> chore: fusion update log msg

builder/vmware/common/driver_parser_test.go, builder/vmware/common/tools_config_test.go
=> fix: remove redundant types

builder/vmware/common/driver_fusion.go
Introduces improvements to the VMware Fusion by enhancing path handling for better security and reliability. It ensures all file paths are sanitized and converted to absolute paths before being used in commands. Additionally, it includes minor code adjustments for compliance with the `gosec` static analysis tool.
**Path Handling Enhancements**:
* Updated all functions (`CompactDisk`, `CreateDisk`, `CreateSnapshot`, `IsRunning`, `Start`, `Stop`, `Clone`) to sanitize file paths using `filepath.Clean` and convert them to absolute paths with `filepath.Abs` before passing them to commands. This prevents potential path traversal vulnerabilities and ensures consistent path handling. [[1]](diffhunk://#diff-064807a60c8abca4575708b28ed413bc78aadd53ada1be0dae276089b51fd5feL49-R60) …
=> chore: clean paths in fusion driver

builder/vmware/common/driver_parser.go, builder/vmware/common/step_configure_vnc.go
Removes redundant type conversion.
=> refactor: redundant type conversion

builder/vmware/iso/step_create_vmx.go
Replaces missed snake_case items from the `vmxTemplateData`.
Follow-up to #311
=> refactor: replace snake case

README.md, version/version.go
=> version: cut release v1.2.0

version/version.go
=> version: prepare v2.0.0-dev

.web-docs/components/builder/iso/README.md, .web-docs/components/builder/vmx/README.md, builder/vmware/common/driver.go, builder/vmware/common/driver_config.go, docs-partials/builder/vmware/common/DriverConfig-not-required.mdx
Adds constants for `fusionAppPath` and `fusionAppPathVariable`.
This change centralizes configuration for fusion settings in the driver layer, improving code organization and maintainability.
Revert commit.
Not applicable.
=> refactor: fusion constants

builder/vmware/iso/builder.go, builder/vmware/vmx/builder.go
Added and updated comments in `builder/vmware/iso/builder.go` and `builder/vmware/vmx/builder.go` to clarify the responsibilities of methods and steps in the build process. Removed unnecessary log import and logging, and improved consistency in comments and code structure for better maintainability.
Removes unnecessary log import and logging, and improved consistency in comments and code structure for better maintainability.
Revert commit.
None.
=> chore: Improve builder clarity

builder/vmware/iso/step_create_vmx.go
Removes outdated `FIXME` comments.
Revert commit.
Not applicable.
=> chore: remove outdated fixme comments

.web-docs/components/builder/vmx/README.md, README.md, builder/vmware/common/driver.go, docs/builders/vmx.mdx
Corrected minor typos, grammar, and improved clarity in comments and documentation. 
These changes enhance readability and maintain consistency in documentation and code comments.
Revert commit.
None.
=> chore: correct typos and grammar

.github/actions/build-and-persist-plugin-binary/action.yml, .github/release.yml, .github/workflows/build_plugin_binaries.yml, .goreleaser.yml
Updates indentation and formatting in GitHub Actions workflows YAML files for improved readability and consistency. No functional changes were made.
Revert commit.
None.
=> chore: yaml formatting in ci and release

builder/vmware/common/driver.go, builder/vmware/common/ssh.go
Refactored the DHCP lease lookup with efficient and maintainable helper methods while maintaining the same functionality.
Closes #321
```shell
packer-plugin-vmware on  refactor/dhcp-lease-lookup [!] via 🐹 v1.25.0 
➜ make test
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/common 6.436s
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/iso    1.494s
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/vmx    1.727s
```
```shell
2025/08/28 19:55:18 packer-plugin-vmware_v2.0.0-dev_x5.0_darwin_arm64 plugin: 2025/08/28 19:55:18 Sending char '/', code 0x2F, shift false
2025/08/28 19:55:18 …
```
=> refactor: dhcp lease lookup
