hashicorp/packer-plugin-vmware

- CHANGELOG.md
- builder/vmware/common/driver.go
- builder/vmware/common/driver_esx5.go
- builder/vmware/common/driver_fusion5.go
- builder/vmware/common/driver_mock.go
- builder/vmware/common/driver_player5.go
- builder/vmware/common/driver_workstation9.go
- builder/vmware/common/step_create_snapshot.go
- builder/vmware/common/step_create_snapshot_test.go
- builder/vmware/iso/builder.go
- builder/vmware/iso/config.go
- builder/vmware/iso/config.hcl2spec.go
- builder/vmware/vmx/builder.go
- builder/vmware/vmx/config.go
- builder/vmware/vmx/config.hcl2spec.go
- docs-partials/builder/vmware/iso/Config-not-required.mdx
- docs-partials/builder/vmware/vmx/Config-not-required.mdx
- main.go
* extended drivers by `CreateSnapshot` method to create snapshots
* added additional step to builders to create initial snapshot of the finished VM (after clean-up)
simply set the `"snapshot_name"` field inside the builder's config to create an initial snapshot (if not set, snapshot creation will be skipped)
Closes #20
> Add Feature: create initial snapshot of VM after clean-up

- builder/vmware/iso/builder.go
- builder/vmware/vmx/builder.go
- builder/vmware/vmx/builder_test.go
This implements support for cd_content
(https://www.packer.io/docs/builders/vmware/vmx#cd_content)
by adding an omitted struct member. Closes #29
> Fix cd_content is ignored

- builder/vmware/common/step_configure_vmx.go
- builder/vmware/iso/builder.go
- builder/vmware/iso/step_create_vmx.go
- builder/vmware/vmx/builder.go
Fix two more issues with vmware and cd_{files,content}
1. if a temporary cdPath is set up, during step_configure_vmx, it should be claned up by step_clean_vmx
There is already [code to do this cleanup](https://github.com/hashicorp/packer-plugin-vmware/blob/e38fb9222041ec935202efd952836aa87fc6d1cb/builder/vmware/common/step_clean_vmx.go#L62-L70), but it wasn't triggering because it was only applied to vmware-iso (and had the wrong device name there). Only floppies were added to temporaryDevices when the setup was actually being done.
2. Fix updating/overwriting existing cdrom device properties (case-sensitivity)
packer lowercases all the vmx keys when reading a file in: https://github.com/hashicorp/packer-plugin-vmware/blob/e38fb9222041ec935202efd952836aa87fc6d1cb/builder/vmware/common/vmx. …
> Fix handling of temporary cdrom devices

- builder/vmware/iso/step_create_vmx.go
This partially reverts commit 048e31aeb6d810f2683dd6a17ab867c3508a8982, fixing a regression caused by #31.
This code was not a mistaken attempt to clean up the device created
for `cd_{files,content}`, as I thought. It was cleaning up the device
(specific to  vmware-iso) on which the `{{ .ISOPath }}` is mounted.
See discussion at https://github.com/hashicorp/packer-plugin-vmware/issues/33#issuecomment-927120617, though this fix doesn't related directly to the original topic of that issue.
> Restore cleanup of temporary vmware-iso device for `iso_path`

- builder/vmware/common/ssh.go
In general those changes allows us to use proxy in order to check the address given it by vmware dhcpd. The changes are rip-off of the original plugin SDK: https://github.com/hashicorp/packer-plugin-sdk/blob/main/communicator/step_connect_ssh.go#L109
The catch here: in general under perfect conditions this change are not needed, because VMware Fusion/workstation connects locally, but if we're using corporate VPN which redirects all the traffic (but localhost) to the corporate network - we can't reach the VM anymore. I found just one way to do so relatively simple: by using SO_DONTROUTE which skips the routing table and allows to communicate directly to the interfaces. So any simple (python/go) proxy with `remote.setsockopt(socket.SOL_SOCKET, socket.SO_DONTROUTE, 1)` will allow to …
> Makes builder to respect ssh_proxy_* configuration

- builder/vmware/iso/builder.go
- builder/vmware/vmx/builder.go
Add `Content` to `StepCreateFloppy` to allow content to be added to floppy device.
Closes #77
> Ensure the contents of `floppy_content` gets added to the configured floppy device

- README.md
- docs/README.md
- Updates `README.md` to follow the same structure as the Packer Plugin for vSphere project, including adding the Requirements section.
- Simplifies `docs/README.md`  to follow the same structure as the Packer Plugin for vSphere project and remove redundant content already provided in the default README.
> **Note**: 
>
> Please review the requirements section. It is based on the content from the lower level `iso.mdx` and `vmx.mdx` content which mentions specific products. In particular, it mentioned VMware Player for Linux, but now Fusion Player (macOS) and Workstation Player (Windows and Linux) exist. As such, I kept it to Workstation Player (Linux) as it may need to be qualified for the Windows and macOS operating systems.
> **Note**: 
>
> Further pull requests for `iso.mdx` and …
> docs: update `README.md` files

- docs/builders/index.mdx
Updated version to the latest 1.0.7, and fixed the source link which was pointing to a non-existence repository on GitHub.
> docs: update version in example

- builder/vmware/common/tools_config.go
- builder/vmware/iso/config.go
- docs-partials/builder/vmware/common/ToolsConfig-not-required.mdx
- docs-partials/builder/vmware/iso/Config-not-required.mdx
- docs/builders/index.mdx
- docs/builders/iso.mdx
- docs/builders/vmx.mdx
With the move to developer.hashicorp.com some links between the general doc and plugins were broken. This PR fixes them
> docs: fix references to internal documentation

- example/data/debian/preseed.pkrtpl.hcl
- example/pkrvars/debian/fusion-12.pkrvars.hcl
- example/pkrvars/debian/fusion-13.pkrvars.hcl
This PR addressed a number of issues that I ran into when testing the provided example. The first issue is the iso url in the example is no longer valid. I updated it to 11.7 the latest minor version of bullseye that has a stable endpoint. The next issue addressed in this pr is in the supplied preseed file. I noticed in testing that the `vagrant` user could not do passwordless sudo. Upon further inspection I could see in `/var/log/installer/syslog` that only the last `sed` late_command was ran. I did some digging and found a number of random SO posts/comments that claimed you can only have a single preseed/late_command. I attempted to find some official Debian documentation that supported that claim and [this](https://lists.debian.org/debian-boot/2016/04/msg00326.html).
This was tested on …
> Combines the example preseed/late_command and updates example iso url to stable 11.7 endpoint

- builder/vmware/common/driver_fusion6.go
This is a hotfix to amend a previous PR supporting VMWare Fusion 13 and it's updated VMTools paths (https://github.com/hashicorp/packer-plugin-vmware/pull/112) 
Closes #137
> fix: fusion 13 x86_x64 vmware tools location

- builder/vmware/common/step_vnc_boot_command.go
- builder/vmware/iso/builder.go
- builder/vmware/vmx/builder.go
- docs/builders/iso.mdx
- docs/builders/vmx.mdx
This change adds the SSHKeyGen step from the SDK.
This step will generate a temporary ssh keypair when there is no ssh password and no ssh key configured.
The code already includes the "StepCleanupTempKeys" step which I believe does nothing without the SSHKeyGen step anyway.
Also included is the ability to use the `SSHPublicKey` variable inside the boot command, I copied this from the VirtualBox builder.
Closes #102
> feat: Add SSHKeyGen Step from SDK

- builder/vmware/iso/step_create_vmx.go
Additional disks would always get configured as scsi devices regardless of `disk_adapter_type`.
This change ensures that additional disks are always configured on the same bus as the primary disk.
Closes #91
> fix: configuration of additional disks

- .web-docs/README.md
- README.md
- docs/README.md
Updates the format and content, as well as add information on the difference between this plugin and `packer-plugin-vsphere`.
Closes #145
> docs: update `README.md`

- go.mod
- go.sum
Bump google.golang.org/protobuf from v1.31.0 to v1.34.1
Ref: https://github.com/hashicorp/packer-plugin-vmware/security/dependabot/27
```console
➜  packer-plugin-vmware git:(chore(deps)/protobuf) go get -u google.golang.org/protobuf
go: downloading google.golang.org/protobuf v1.34.1
go: upgraded google.golang.org/protobuf v1.31.0 => v1.34.1
➜  packer-plugin-vmware git:(chore(deps)/protobuf) ✗ go mod tidy
go: downloading github.com/stretchr/objx v0.5.2
➜  packer-plugin-vmware git:(chore(deps)/protobuf) ✗ make build
➜  packer-plugin-vmware git:(chore(deps)/protobuf) ✗ make test
ok …
```
> chore(deps): bump google.golang.org/protobuf from v1.31.0 to v1.34.1

- .golangci.yml
- builder/vmware/common/driver.go
- builder/vmware/common/driver_fusion5.go
- builder/vmware/common/ssh_config_test.go
- builder/vmware/common/step_clean_vmx_test.go
- builder/vmware/common/step_configure_vmx_test.go
- builder/vmware/common/step_output_dir_test.go
- builder/vmware/common/step_prepare_tools_test.go
- builder/vmware/common/step_shutdown_test.go
- builder/vmware/common/vmx.go
- builder/vmware/iso/builder_acc_test.go
- builder/vmware/iso/builder_test.go
- builder/vmware/iso/config.go
- builder/vmware/iso/step_create_vmx.go
- builder/vmware/iso/step_create_vmx_test.go
- builder/vmware/vmx/builder_test.go
- builder/vmware/vmx/config_test.go
- builder/vmware/vmx/step_clone_vmx_test.go
`io/ioutil` is deprecated as of Go 1.16:
- Updates `ioutil.TempDir` to `os.MkdirTemp`.
- Updates `ioutil.TempFile` to `os.CreateTemp`.
- Updates `ioutil.ReadFile` to `os.ReadFile`.
- Updates `ioutil.WriteFile` to `os.WriteFile`.
- Updates `ioutil.ReadAll` to `io.ReadAll`.
```console
packer-plugin-vmware on  chore/ioutil-depreciation via 🐹 v1.22.3 
2024/05/11 01:00:04 Copying "docs" to ".docs/"
2024/05/11 01:00:04 Replacing @include '...' calls in .docs/
packer-plugin-vmware on  chore/ioutil-depreciation via 🐹 v1.22.3 
➜ make build   
packer-plugin-vmware on  chore/ioutil-depreciation via 🐹 v1.22.3 took 2.6s 
➜ make test    
? …
```
> chore: address io/ioutil depreciation

- go.mod
- go.sum
Bump golang/x/net from 0.21.0 to 0.25.0.
- GHSA-4v7x-pqxf-cx7m
Ref: https://github.com/hashicorp/packer-plugin-vmware/security/dependabot/26
```shell
➜  packer-plugin-vmware git:(chore(deps)/golang-x-net) go get -u golang.org/x/net
go: downloading golang.org/x/net v0.25.0
➜  packer-plugin-vmware git:(chore(deps)/golang-x-net) ✗ go mod tidy
➜  packer-plugin-vmware git:(chore(deps)/golang-x-net) ✗ make build
➜  packer-plugin-vmware git:(chore(deps)/golang-x-net) ✗ make test
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/common 7.111s
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/iso    2.917s
ok …
```
> chore(deps): bump golang/x/net from 0.21.0 to 0.25.0

- builder/vmware/common/driver_esx5.go
TrailingComma has been deprecated since Go 1.2.
```shell
packer-plugin-vmware on  chore/trailingcomma-depreciation via 🐹 v1.22.3 
2024/05/14 19:17:46 Copying "docs" to ".docs/"
2024/05/14 19:17:46 Replacing @include '...' calls in .docs/
packer-plugin-vmware on  chore/trailingcomma-depreciation via 🐹 v1.22.3 
➜ make build   
packer-plugin-vmware on  chore/trailingcomma-depreciation via 🐹 v1.22.3 took 3.0s 
➜ make test
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/common 6.606s
ok …
```
> chore: address trailingcomma depreciation

- builder/vmware/common/driver_config_test.go
- builder/vmware/common/run_config_test.go
Replaces the use of `reflect.DeepEqual` with `errors.Is` for error comparison.
```console
packer-plugin-vmware on  chore/replace-reflect.DeepEqual [!] via 🐹 v1.22.3 
2024/05/25 00:44:22 Copying "docs" to ".docs/"
2024/05/25 00:44:22 Replacing @include '...' calls in .docs/
packer-plugin-vmware on  chore/replace-reflect.DeepEqual [!] via 🐹 v1.22.3 took 4.7s 
➜ make build   
packer-plugin-vmware on  chore/replace-reflect.DeepEqual [!] via 🐹 v1.22.3 took 3.0s 
➜ make test
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/common 6.592s
ok …
```
> chore: replace `reflect.DeepEqual`

- .web-docs/components/builder/iso/README.md
- .web-docs/components/builder/vmx/README.md
- builder/vmware/common/driver.go
- builder/vmware/common/driver_player_unix.go
- builder/vmware/common/driver_workstation_unix.go
- builder/vmware/common/hw_config.go
- builder/vmware/common/run_config.go
- builder/vmware/common/step_configure_vmx.go
- builder/vmware/common/step_shutdown.go
- builder/vmware/common/tools_config.go
- builder/vmware/vmx/config.go
- docs-partials/builder/vmware/common/ParallelUnion.mdx
- docs-partials/builder/vmware/common/RunConfig-not-required.mdx
- docs-partials/builder/vmware/common/SerialConfigPipe.mdx
- docs-partials/builder/vmware/common/ToolsConfig-not-required.mdx
- docs-partials/builder/vmware/vmx/Config.mdx
- docs/builders/iso.mdx
Updates "VMWare" to "VMware".
```shell
packer-plugin-vmware on  docs/correct-brand-name
➜ go fmt ./...
packer-plugin-vmware on  docs/correct-brand-name
2024/06/25 22:50:36 Copying "docs" to ".docs/"
2024/06/25 22:50:36 Replacing @include '...' calls in .docs/
packer-plugin-vmware on  docs/correct-brand-name
➜ make build
packer-plugin-vmware on  docs/correct-brand-name
➜ make test
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/common 6.600s
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/iso    2.283s
ok …
```
> docs: correct brand name

- go.mod
- go.sum
Updates `github.com/hashicorp/go-retryablehttp` from v0.7.0 => v0.7.7.
```console
packer-plugin-vmware on  chore(deps)/retryablehttp
✦ ➜ go get -u github.com/hashicorp/go-retryablehttp
go: downloading github.com/hashicorp/go-retryablehttp v0.7.7
go: upgraded github.com/fatih/color v1.14.1 => v1.16.0
go: upgraded github.com/hashicorp/go-hclog v1.5.0 => v1.6.3
go: upgraded github.com/hashicorp/go-retryablehttp v0.7.0 => v0.7.7
go: upgraded github.com/mattn/go-isatty v0.0.17 => v0.0.20
packer-plugin-vmware on  chore(deps)/retryablehttp
✦ ➜ go mod tidy
packer-plugin-vmware on  chore(deps)/retryablehttp
✦ ➜ go fmt ./... 
packer-plugin-vmware on  chore(deps)/retryablehttp
✦ ➜ make generate
2024/06/25 19:45:47 Copying "docs" to ".docs/"
2024/06/25 19:45:47 Replacing @include '...' calls in …
```
> chore(deps): hashicorp/go-retryablehttp

- builder/vmware/iso/builder.go
- builder/vmware/vmx/builder.go
Moves `&communicator.StepSSHKeyGen` position to earlier in each builder.
```shell
packer-plugin-vmware on  fix/update-stepsshkeygen-postion
✦ ➜ go fmt ./...
packer-plugin-vmware on  fix/update-stepsshkeygen-postion
✦ ➜ make generate
2024/06/25 20:07:52 Copying "docs" to ".docs/"
2024/06/25 20:07:52 Replacing @include '...' calls in .docs/
packer-plugin-vmware on  fix/update-stepsshkeygen-postion
✦ ➜ make build
packer-plugin-vmware on  fix/update-stepsshkeygen-postion
✦ ➜ make test
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/common 7.279s
ok …
```
> fix: update `StepSSHKeyGen` position

- .web-docs/components/builder/iso/README.md
- builder/vmware/iso/config.go
- builder/vmware/iso/config.hcl2spec.go
- builder/vmware/iso/step_create_vmx.go
- docs-partials/builder/vmware/iso/Config-not-required.mdx
Adds explicit option to enable virtual hardware-assisted virtualization.
`vhv_enabled` (bool) - Enable virtual hardware-assisted virtualization for the virtual machine. Defaults to `false`.
```hcl
vhv_enabled = true
```
```console
packer-plugin-vmware on  feat/enable-vhv
➜ go fmt ./...
packer-plugin-vmware …
2024/07/02 00:33:05 Copying "docs" to ".docs/"
2024/07/02 00:33:05 Replacing @include '...' calls in .docs/
packer-plugin-vmware on  feat/enable-vhv
➜ make build
packer-plugin-vmware on  feat/enable-vhv
➜ make dev
Successfully installed plugin github.com/hashicorp/vmware from /Users/ryan/Library/Mobile …
```
> feat: enable virtual hardware-assisted virtualization

- .web-docs/components/builder/iso/README.md
- .web-docs/components/builder/vmx/README.md
- builder/vmware/common/export_config.go
- docs-partials/builder/vmware/common/ExportConfig-not-required.mdx
Refactors to use `allowedFormatValues` for export options.
```console
packer-plugin-vmware on  refactor/export-formats
➜ go fmt ./... 
packer-plugin-vmware on  refactor/export-formats
2024/07/02 23:39:08 Copying "docs" to ".docs/"
2024/07/02 23:39:08 Replacing @include '...' calls in .docs/
packer-plugin-vmware on  refactor/export-formats
➜ make build
packer-plugin-vmware on  refactor/export-formats
➜ make test
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/common 6.625s
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/iso …
```
> refactor: export formats

- .web-docs/components/builder/iso/README.md
- builder/vmware/common/hw_config.go
- builder/vmware/iso/config.hcl2spec.go
- builder/vmware/iso/step_create_vmx.go
- docs-partials/builder/vmware/common/HWConfig-not-required.mdx
Adds options to explicitly enable UEFI and Secure Boot (requires UEFI).
Introduces optional `firmware`. Allowed values are `bios`, `uefi`, and `uefi-secure` (for secure boot).  Defaults to the recommended firmware type for the guest operating system.
Note the use of "uefi" instead of "efi" as seen in `packer-plugin-vsphere` as this is more correct and aligns with the UI and the secure boot key in the `.vmx` file.
```console
packer-plugin-vmware on  feat/uefi-secure-boot
➜ go fmt ./...
packer-plugin-vmware on  feat/uefi-secure-boot
2024/06/30 23:20:31 Copying "docs" to ".docs/"
2024/06/30 23:20:31 Replacing @include '...' calls in .docs/
packer-plugin-vmware on  feat/uefi-secure-boot [$!]
➜ make build …
```
> feat: add uefi and secure boot

- builder/vmware/common/driver_player5_windows.go
- builder/vmware/common/driver_player6_windows.go
- builder/vmware/common/driver_player_unix.go
- builder/vmware/common/driver_workstation10_windows.go
- builder/vmware/common/driver_workstation9_windows.go
- builder/vmware/common/driver_workstation_unix.go
- builder/vmware/common/driver_workstation_unix_test.go
Removes the legacy `// +build` syntax.
The `//go:build` syntax was introduced in Go 1.17 to replace the older `// +build` syntax, offering a more readable and flexible way to specify build constraints.
For Go 1.17 and later:
- Use the `//go:build` syntax for specifying build constraints.
- The `// +build` syntax is still recognized for backward compatibility but is considered deprecated in new code.
For Go versions before 1.17:
- Only the `// +build` syntax is recognized
Based on the version used in this project, the use of the following:
```go
//go:build !windows
// +build !windows
```
... can be simplified to:
```go
//go:build !windows
```
> chore: remove legacy `// +build` syntax

- .web-docs/components/builder/iso/README.md
- .web-docs/components/builder/vmx/README.md
- builder/vmware/common/run_config.go
- builder/vmware/common/run_config_test.go
- docs-partials/builder/vmware/common/RunConfig-not-required.mdx
- docs-partials/builder/vmware/common/RunConfig.mdx
- docs/builders/iso.mdx
- docs/builders/vmx.mdx
- Updates comments for more streamlined documentation.
- Removes the use of "magic" numbers and defines constants.
```console
packer-plugin-vmware on  chore-update-run-config [$✘!] via 🐹 v1.22.5 took 10.0s 
➜ go fmt ./... 
builder/vmware/common/run_config_test.go
packer-plugin-vmware on  chore-update-run-config [$✘!] via 🐹 v1.22.5 
2024/07/07 23:09:07 Copying "docs" to ".docs/"
2024/07/07 23:09:07 Replacing @include '...' calls in .docs/
packer-plugin-vmware on  chore-update-run-config [$✘!] via 🐹 v1.22.5 
➜ make build   
packer-plugin-vmware on  chore-update-run-config [$✘!] via 🐹 v1.22.5 
➜ make test    
? …
```
> chore: update run config

- .web-docs/components/builder/iso/README.md
- .web-docs/components/builder/vmx/README.md
- builder/vmware/common/disk_config.go
- docs-partials/builder/vmware/common/DiskConfig-not-required.mdx
Updates the disk configuration documentation for clarity and readability.
```console
packer-plugin-vmware on  docs/update-disk-configuration
➜ go fmt ./... 
packer-plugin-vmware on  docs/update-disk-configuration
2024/07/08 14:55:29 Copying "docs" to ".docs/"
2024/07/08 14:55:29 Replacing @include '...' calls in .docs/
packer-plugin-vmware on  docs/update-disk-configuration
➜ make build     
packer-plugin-vmware on  docs/update-disk-configuration
➜ make test 
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/common 7.263s
ok …
```
> docs: update disk configuration

- .web-docs/components/builder/iso/README.md
- .web-docs/components/builder/vmx/README.md
- builder/vmware/common/driver_config.go
- builder/vmware/common/driver_esx5.go
- builder/vmware/common/output_config.go
- builder/vmware/common/step_configure_vmx.go
- builder/vmware/common/step_output_dir.go
- builder/vmware/common/step_register.go
- docs-partials/builder/vmware/common/DriverConfig-not-required.mdx
- docs-partials/builder/vmware/common/OutputConfig-not-required.mdx
Sweeps and corrects the following terms:
- "ESX" to "ESXi"
- "server" to "host"
- "remote esx" to "remote hypervisor"
> docs: term corrections

- .web-docs/components/builder/iso/README.md
- .web-docs/components/builder/vmx/README.md
- builder/vmware/common/vmx_config.go
- docs-partials/builder/vmware/common/VMXConfig-not-required.mdx
Updates the documentation for the `.vmx` file configuration.
```console
packer-plugin-vmware on  docs/update-vmxconfig
➜ go fmt ./... 
packer-plugin-vmware on  docs/update-vmxconfig
2024/07/15 14:03:04 Copying "docs" to ".docs/"
2024/07/15 14:03:04 Replacing @include '...' calls in .docs/
packer-plugin-vmware on  docs/update-vmxconfig
➜ make test
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/common 7.237s
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/iso    2.611s
ok …
```
> docs: update vmxconfig

- builder/vmware/common/ssh_config.go
Deprecate `ssh_skip_request_pty` per comment:
https://github.com/hashicorp/packer-plugin-vmware/blob/330dc55d3b00bab6d95ae17ae541ce55f5efb50e/builder/vmware/common/ssh_config.go#L13-L19
```console
packer-plugin-vmware on  chore/remove-ssh_skip_request_pty [$!] via 🐹 v1.22.5 
⇣7% ➜ go fmt ./... 
packer-plugin-vmware on  chore/remove-ssh_skip_request_pty [$!] via 🐹 v1.22.5 
⇣7% ➜ make generate
2024/07/07 22:12:12 Copying "docs" to ".docs/"
2024/07/07 22:12:12 Replacing @include '...' calls in .docs/
packer-plugin-vmware on  chore/remove-ssh_skip_request_pty [$!] via 🐹 v1.22.5 
⇣7% ➜ make build   
packer-plugin-vmware on  chore/remove-ssh_skip_request_pty [$!] via 🐹 v1.22.5 took 3.2s 
⇣7% ➜ make test
? …
```
> chore: deprecate `ssh_skip_request_pty`

- builder/vmware/common/step_create_snapshot.go
- builder/vmware/common/step_create_snapshot_test.go
- builder/vmware/iso/builder.go
- builder/vmware/vmx/builder.go
Moves the snapshot creation step after the upload of the `.vmx` file to the remote hypervisor. When not set in this order, the virtual machine will not be set to run on the created snapshot.
General
```console
packer-plugin-vmware on  fix/snapshot-creation [$!] via 🐹 v1.22.5 took 3.4s 
➜ go fmt ./...
packer-plugin-vmware on  fix/snapshot-creation [$!] via 🐹 v1.22.5 
2024/07/15 22:04:53 Copying "docs" to ".docs/"
2024/07/15 22:04:53 Replacing @include '...' calls in .docs/
packer-plugin-vmware on  fix/snapshot-creation [$!] via 🐹 v1.22.5 took 2.9s 
➜ make build
packer-plugin-vmware on  fix/snapshot-creation [$!] via 🐹 v1.22.5 
➜ make test
? …
```
> fix: remote hypervisor snapshot creation

- version/version.go
- Updates `version/version.go` as v1.1.0 dev.
- Replaces the deprecated `InitializePluginVersion` with `NewPluginVersion` from `packer-plugin-sdk`, which is the recommended approach.
- Removed superfluous comments that are already included in the SDK.
```console
packer-plugin-vmware on  chore/update-version [$] via 🐹 v1.22.6 
➜ make dev
Successfully installed plugin github.com/hashicorp/vmware from /Users/johnsonryan/Library/Mobile Documents/com~apple~CloudDocs/Code/Work/packer-plugin-vmware/packer-plugin-vmware to /Users/johnsonryan/.packer.d/plugins/github.com/hashicorp/vmware/packer-plugin-vmware_v1.1.0-dev_x5.0_darwin_amd64
```
> chore: v1.1.0 dev

- builder/vmware/common/driver.go
- builder/vmware/common/driver_esx5.go
- builder/vmware/common/step_export.go
Checks the minimum recommended version of VMware Open Virtualization Format Tool ('ovftool').
Sets the minimum recommended to 4.6.0 to support vSphere 8.0 and earlier.
Also improves the documentation for Export Configuration that uses `ovftool`.
✅ Basic Tests
```console
packer-plugin-vmware on  feat/check-ovftool-version
✦ ➜ go fmt ./...
packer-plugin-vmware on  feat/check-ovftool-version
✦ ➜ make generate
2024/08/08 18:43:42 Copying "docs" to ".docs/"
2024/08/08 18:43:42 Replacing @include '...' calls in .docs/
packer-plugin-vmware on  feat/check-ovftool-version
✦ ➜ make build
packer-plugin-vmware on  feat/check-ovftool-version
✦ ➜ make test
? …
```
> feat: check ovftool version

- .web-docs/components/builder/iso/README.md
- .web-docs/components/builder/vmx/README.md
- builder/vmware/common/driver_config.go
- builder/vmware/common/driver_config_test.go
- docs-partials/builder/vmware/common/DriverConfig-not-required.mdx
- Updated the docs for the driver configuration.
- Updated the error messages and corresponding tests for clarity and to be more idiomatic.
> chore: update `driver_config.go`

- .github/workflows/codeql-analysis.yml
- README.md
- go.mod
Adds CodeQL Analysis.
Required 1.N.P syntax in `go.mod` which is used in `go.version`.
(Also moved `hashicorp/go-version` to a direct requirement.)
> chore(ci): add codeql analysis

- builder/vmware/iso/step_create_vmx.go
This modification ensures that both `isoPath` is an absolute path.
Basic:
```console
packer-plugin-vmware on  fix/relative-paths via 🐹 v1.23.0 
⇣8% ➜ go fmt ./...
packer-plugin-vmware on  fix/relative-paths via 🐹 v1.23.0 
⇣8% ➜ make build
packer-plugin-vmware on  fix/relative-paths via 🐹 v1.23.0 
⇣8% ➜ make test
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/common 6.632s
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/iso    1.766s
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/vmx    2.182s
```
E2E:
```hcl
iso_checksum     = var.iso_checksum
iso_url          = var.iso_url …
```
> fix: isoPath as absolute path

- builder/vmware/common/driver.go
This pull request includes a small change to the `builder/vmware/common/driver.go` file. The change adds a comment to ignore a specific lint warning.
* [`builder/vmware/common/driver.go`](diffhunk://#diff-f2729c057c901fdc3e94cc6999b57818480a13abecfb0fccb5b7a0fccfbf7be3R639): Added a comment to ignore the `SA4010` lint warning in the `HostAddress` function.
> fix: ignore sa4010

- builder/vmware/common/driver_fusion.go
Sets the information log messages in the Fusion driver to be prefaces with [INFO].
```shell
packer-plugin-vmware on  chore/fusion-log-messages [$] via 🐹 v1.23.2 
➜ go fmt ./...
packer-plugin-vmware on  chore/fusion-log-messages [$] via 🐹 v1.23.2 
➜ make test
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/common 7.531s
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/iso    1.550s
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/vmx    1.967s
packer-plugin-vmware on  chore/fusion-log-messages [$] via 🐹 v1.23.2 took 23.4s 
➜ make build
packer-plugin-vmware on  chore/fusion-log-messages …
```
> chore: fusion log messages

- builder/vmware/common/driver.go
- builder/vmware/common/driver_fusion.go
- builder/vmware/common/driver_player.go
- builder/vmware/common/driver_player_unix.go
- builder/vmware/common/driver_player_windows.go
- builder/vmware/common/driver_workstation10.go
- builder/vmware/common/driver_workstation10_windows.go
- builder/vmware/common/driver_workstation_unix.go
- Updates the version checks, using `hashicorp/go-version`.
- Updates log messages based on `INFO` or `WARN` context.
- Moves constants to the `driver.go` for easier maintenance.
```sh
➜ make build
packer-plugin-vmware on  pr/262 via 🐹 v1.23.3 
➜ make test
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/common 7.042s
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/iso    2.665s
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/vmx    3.531s
packer-plugin-vmware on  pr/262 via 🐹 v1.23.3 took 10.2s 
2024/12/02 10:47:55 Copying "docs" to ".docs/"
2024/12/02 10:47:55 Replacing …
```
> fix: version checks

- builder/vmware/vmx/step_clone_vmx.go
- example/variables.pkr.hcl
Updates legacy [kb.vmware.com](https://kb.vmware.com) links to [knowledge.broadcom.com](https://knowledge.broadcom.com).
> chore: update kb links

- go.mod
- go.sum
Bumps bump github.com/go-jose/go-jose/v4 v4.0.1 to v4.0.5.
[CVE-2025-27144](https://github.com/hashicorp/packer-plugin-vmware/security/dependabot/33)
```shell
packer-plugin-vmware on  chore(deps)/go-jose [!] via 🐹 v1.24.1 took 4.1s 
➜ go get -u github.com/go-jose/go-jose/v4
go: downloading golang.org/x/crypto v0.32.0
go: upgraded github.com/go-jose/go-jose/v4 v4.0.1 => v4.0.5
go: upgraded golang.org/x/crypto v0.31.0 => v0.36.0
go: upgraded golang.org/x/sys v0.28.0 => v0.31.0
go: upgraded golang.org/x/term v0.27.0 => v0.30.0
packer-plugin-vmware on  chore(deps)/go-jose [!] via 🐹 v1.24.1 took 4.1s 
➜ go mod tidy                            
packer-plugin-vmware on  chore(deps)/go-jose [!] via 🐹 v1.24.1 
➜ make build                             
packer-plugin-vmware on  …
```
> chore(deps): bump github.com/go-jose/go-jose/v4 v4.0.1 to v4.0.5

- builder/vmware/common/driver.go
- builder/vmware/common/driver_workstation_unix.go
- builder/vmware/common/driver_workstation_unix_test.go
Refactors `workstationLicenseCheck` to enhance the handling of VMware Workstation license checks and improve test coverage. The most important changes include adding a new constant for a version that does not require a license, modifying the license check logic, and adding comprehensive unit tests for the updated logic.
Enhancements to license handling:
* [`builder/vmware/common/driver.go`](diffhunk://#diff-f2729c057c901fdc3e94cc6999b57818480a13abecfb0fccb5b7a0fccfbf7be3R32-R37): Added a new constant `workstationNoLicenseVersion` for version 17.6.2, which no longer requires a license for use - free for personal and commercia use - and provided notes and references for version changes.
* [`builder/vmware/common/driver_workstation_unix.go`](diffhunk://#diff-bbe4c1aa0333c30034450736a5adde34d6 …
> refactor: workstation license check

- builder/vmware/common/driver.go
- builder/vmware/common/driver_esxi.go
- builder/vmware/common/driver_fusion.go
- builder/vmware/iso/step_create_vmx_test.go
Refactors to use `strings.ReplaceAll` as it more clearly expresses the intent to replace all occurrences of the substring and is the idiomatic Go approach for this use case since Go 1.12.
> refactor: use `strings.ReplaceAll`

- builder/vmware/common/driver.go
- builder/vmware/common/driver_parser.go
While functionally identical, the updated form is generally preferred because it's often considered more readable and directly expresses the required state of the variable. ref: De Morgan's laws.
> refactor: directly express required state

- builder/vmware/common/step_configure_vmx.go
Replace the if-else if-else block used to determine the value of `diskData.CDROMType_PrimarySecondary` based on `cdromAdapterType` with an equivalent switch statement.
The switch statement improves readability and is the more idiomatic Go construct when evaluating a single variable against multiple distinct conditions (empty string, matching `diskAdapterType`, or default).
This change preserves the original logic and behavior.
> refactor: use switch cdromAdapterType

- builder/vmware/common/driver_fusion.go
- builder/vmware/common/driver_player.go
- builder/vmware/common/driver_workstation10.go
- builder/vmware/common/driver_workstation9.go
- builder/vmware/common/ssh.go
- builder/vmware/iso/builder.go
- builder/vmware/iso/builder_test.go
- builder/vmware/iso/config.go
- builder/vmware/iso/step_create_vmx.go
- builder/vmware/vmx/builder.go
- builder/vmware/vmx/builder_test.go
- builder/vmware/vmx/config.go
Refactored multiple instances where methods or fields were accessed through an intermediate field. These have been simplified to use direct access where applicable.
```shell
~/Downloads/packer-plugin-vmware git:[refactor/simplify-intermediate-access]
make generate
2025/04/27 20:53:09 Copying "docs" to ".docs/"
2025/04/27 20:53:09 Replacing @include '...' calls in .docs/
~/Downloads/packer-plugin-vmware git:[refactor/simplify-intermediate-access]
make dev
Successfully installed plugin github.com/hashicorp/vmware from /Users/johnsonryan/Downloads/packer-plugin-vmware/packer-plugin-vmware to /Users/johnsonryan/.packer.d/plugins/github.com/hashicorp/vmwar …
```
> refactor: simplify access to methods/fields via direct calls

- builder/vmware/common/driver_mock.go
- builder/vmware/common/driver_parser.go
- builder/vmware/common/driver_parser_test.go
- builder/vmware/iso/step_create_vmx.go
Replaces `foo += 1` with `foo++`.
This change follows Go's idiomatic style by using the `++` operator instead of `+= 1` for incrementing variables. The `++` operator is more concise and is the standard way to increment loop counters in Go.
> refactor: replace `foo += 1` with `foo++`

- builder/vmware/common/driver_parser.go
- builder/vmware/common/driver_parser_test.go
- Fix `revive` linter warnings related to `superfluous-else`.
- Move variable declarations to their own lines where needed.
- Simplify conditional blocks that had breaks followed by else clauses.
- Maintain identical functionality while improving code readability.
> refactor: remove superfluous else

- builder/vmware/common/driver_workstation9.go
- builder/vmware/common/ssh_config_test.go
- builder/vmware/common/step_clean_vmx_test.go
- builder/vmware/common/step_shutdown_test.go
- builder/vmware/vmx/step_clone_vmx_test.go
Adds `//nolint:gosec` for:
- Expected permission value for `.plist` file.
- Expected permission value for sample `.vmx` file for tests.
- Expected permission value for sample `.lock` file for tests.
- Sample PEM file for tests.
**Suppression of `gosec` linting warnings**:
* Added `//nolint:gosec` to `os.WriteFile` calls in `generateNetmapConfig` to bypass security linting for file permission issues. (`builder/vmware/common/driver_workstation9.go`, [builder/vmware/common/driver_workstation9.goL343-R343](diffhunk://#diff-9c1eac421dbc07a58019d9e0de8411cba0c97dbcd330a425d19d8585584100a7L343-R343))
* Added `//nolint:gosec` comments to `os.WriteFile` calls in the following test cases to suppress security warnings:
- `TestStepCleanVMX_floppyPath` (`builder/vmware/common/step_clean_vmx_test.go`, …
> chore: nolint gosec

- .github/workflows/go-validate.yml
- .golangci.yml
Updates `golangci-lint` to v2 (`latest`).
- Migrated the configuration.
- Updates the `golangci/golangci-lint-action` to v7 for interoperability.
> chore: update golangci-lint to v2

- builder/vmware/iso/builder_acc_test.go
- builder/vmware/iso/step_create_vmx_test.go
Error strings should not be capitalized or end with punctuation.
```shell
~/Downloads/packer-plugin-vmware git:[fix/error-strings-casing]
go fmt ./...
~/Downloads/packer-plugin-vmware git:[fix/error-strings-casing]
make dev
Successfully installed plugin github.com/hashicorp/vmware from /Users/johnsonryan/Downloads/packer-plugin-vmware/packer-plugin-vmware to /Users/johnsonryan/.packer.d/plugins/github.com/hashicorp/vmware/packer-plugin-vmware_v1.1.1-dev_x5.0_darwin_amd64
~/Downloads/packer-plugin-vmware git:[fix/error-strings-casing]
make build
~/Downloads/packer-plugin-vmware git:[fix/error-strings-casing]
make test
ok …
```
> fix: error strings casing

- builder/vmware/common/driver_parser_test.go
Removes redundant type.
```shell
~/Downloads/packer-plugin-vmware git:[refactor/remove-redundant-type]
go fmt ./...
~/Downloads/packer-plugin-vmware git:[refactor/remove-redundant-type]
make dev
Successfully installed plugin github.com/hashicorp/vmware from /Users/johnsonryan/Downloads/packer-plugin-vmware/packer-plugin-vmware to /Users/johnsonryan/.packer.d/plugins/github.com/hashicorp/vmware/packer-plugin-vmware_v1.1.1-dev_x5.0_darwin_amd64
~/Downloads/packer-plugin-vmware git:[refactor/remove-redundant-type]
make build
~/Downloads/packer-plugin-vmware git:[refactor/remove-redundant-type]
make test
ok …
```
> refactor: remove redundant type

- builder/vmware/common/driver_workstation10.go
Removes unused constant: `VMWARE_WS_VERSION`.
> chore: remove unused constant

- builder/vmware/common/driver.go
- builder/vmware/common/driver_esxi.go
Replaces type assertion on errors with a call to `errors.As`.
The preferred way for checking for a specific error type is to use the `errors.As` function from the standard library as this function traverses the chain of the wrapped errors while checking for a specific error type.
```shell
~/Downloads/packer-plugin-vmware git:[refactor/replaces-type-assertion]
go fmt ./...
~/Downloads/packer-plugin-vmware git:[refactor/replaces-type-assertion]
make dev
Successfully installed plugin github.com/hashicorp/vmware from /Users/johnsonryan/Downloads/packer-plugin-vmware/packer-plugin-vmware to /Users/johnsonryan/.packer.d/plugins/github.com/hashicorp/vmware/packer-plugin-vmware_v1.1.1-dev_x5.0_darwin_amd64 …
```
> refactor: replace type assertion on errors

- builder/vmware/common/driver_parser_test.go
`reading` would always be true. ut simplifying would leave it not used.
So, therefore refactored the loop using built-in `range` keyword for channels, which provides a more concise and readable way to iterate through channel values until the channel is closed.
```shell
~/Downloads/packer-plugin-vmware git:[refactor/simplify-channel-reading]
make test
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/common 6.901s
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/iso    2.241s
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/vmx    2.737s
```
> refactor: simplify channel reading with range

- builder/vmware/common/driver_parser.go
- builder/vmware/common/driver_parser_test.go
Renaming variable overlap with a used import, `errors`.
```shell
~/Downloads/packer-plugin-vmware git:[refactor/variable-overlap-with-used-import]
go fmt ./...
~/Downloads/packer-plugin-vmware git:[refactor/variable-overlap-with-used-import]
make dev
Successfully installed plugin github.com/hashicorp/vmware from /Users/johnsonryan/Downloads/packer-plugin-vmware/packer-plugin-vmware to /Users/johnsonryan/.packer.d/plugins/github.com/hashicorp/vmware/packer-plugin-vmware_v1.1.1-dev_x5.0_darwin_amd64
~/Downloads/packer-plugin-vmware git:[refactor/variable-overlap-with-used-import]
make build
~/Downloads/packer-plugin-vmware git:[refactor/variable-overlap-with-used-import]
make test
? …
```
> refactor: variable overlap with used import

- main.go
Refactor fatal error handling in the main function to use `log.Fatal`.
Previously, fatal errors were handled by printing to os.Stderr using `fmt.Fprintln` followed by an explicit `os.Exit(1)`.This change replaces that pattern with a single call to `log.Fatal(err)`. This is more idiomatic Go, makes the code more concise, and leverages the standard log package's capabilities, such as automatic timestamping of the error message. The program's exit behavior (exiting with status 1 on fatal error) remains the same.
```shell
~/Downloads/packer-plugin-vmware git:[refactor/standardize-fatal-error-handling]
go fmt ./...
~/Downloads/packer-plugin-vmware git:[refactor/standardize-fatal-error-handling]
make dev …
```
> refactor: use `log.Fatal` for fatal error handling in `main`

- builder/vmware/common/ssh_config.go
- builder/vmware/iso/config.hcl2spec.go
- builder/vmware/vmx/config.hcl2spec.go
This pull request cleans up the `builder/vmware/common/ssh_config.go` file by removing deprecated code and unnecessary imports. The most important changes are focused on deprecating the `ssh_skip_request_pty` option and simplifying the `Prepare` method.
Deprecation and code cleanup:
* Removed the deprecated `SSHSkipRequestPty` field and its related logic from the `SSHConfig` struct and `Prepare` method. This option is no longer supported and the warning log has been eliminated.
* Removed the unused `log` import since logging for deprecation is no longer needed.
Removes deprecated code and unnecessary imports.
Revert commit.
None.
> refactor: remove `ssh_skip_request_pty`

- builder/vmware/common/driver.go
This pull request updates the version check logic for `ovftool` in the driver. Instead of logging a warning when the installed version is below the minimum required, it now returns an error, enforcing stricter compatibility requirements.
The `CheckOvfToolVersion` function in `builder/vmware/common/driver.go` now returns an error if the detected `ovftool` version is below the minimum required, rather than just logging a warning. This change ensures that builds will fail early if an incompatible version is detected.
Error handling and compatibility enforcement.
Revert commit.
None.
> refactor: enforce minimum ovftool version

- builder/vmware/common/driver_workstation.go
Changed parameter names in `WorkstationDriver.CreateDisk` from `snake_case` to `camelCase` for consistency with Go naming conventions.
None.
Revert commit.
None.
> chore: remove snake case

- builder/vmware/common/driver.go
- builder/vmware/common/export_config.go
- builder/vmware/common/hw_config.go
- builder/vmware/common/step_clean_files.go
- builder/vmware/common/tools_config.go
- builder/vmware/iso/config.go
- builder/vmware/vmx/config.go
Centralizes the definitions of allowed values and constants for export formats, firmware types, file extensions, and VMware Tools flavors by moving them from individual config files into `builder/vmware/common/driver.go`. This improves maintainability and reduces duplication across the codebase.
* Moved the export format constants (`ovf`, `ova`, `vmx`) and the `allowedExportFormats` list from `export_config.go` to `driver.go`, and removed their previous definitions. [[1]](diffhunk://#diff-f2729c057c901fdc3e94cc6999b57818480a13abecfb0fccb5b7a0fccfbf7be3R110-R119) [[2]](diffhunk://#diff-f2729c057c901fdc3e94cc6999b57818480a13abecfb0fccb5b7a0fccfbf7be3R129-R149) [[3]](diffhunk://#diff-7158161d20d6e82e3ff987e7f165940344bb108b246bba667af9dceac9502eb5L16-L26)
* Moved the allowed firmware types …
> refactor: centralize allowed values and constants

- builder/vmware/common/driver.go
- builder/vmware/common/step_clean_files.go
- builder/vmware/iso/config.go
- builder/vmware/vmx/config.go
This pull request introduces improvements to naming conventions and file cleanup logic in the codebase. The most notable changes include the introduction of a centralized default resource name prefix, updates to virtual machine naming logic to use this prefix, and a refactor of file extension handling for cleanup operations.
**Naming convention improvements:**
* Added `DefaultNamePrefix` constant (`"packer"`) to `builder/vmware/common/driver.go` for consistent resource naming across the system.
* Updated VM name generation in `builder/vmware/iso/config.go` and `builder/vmware/vmx/config.go` to use the new `DefaultNamePrefix` instead of hardcoded `"packer"` strings, ensuring consistency in VM naming. [[1]](diffhunk://#diff-6a22861e2ec726ec0cc6112f8892aacd7cc6f3a86c1c53cace1357f215fad35eL157 …
> refactor: naming prefix constant

- builder/vmware/common/driver.go
- builder/vmware/common/driver_workstation.go
- builder/vmware/common/driver_workstation_unix.go
- builder/vmware/common/hw_config.go
- builder/vmware/common/tools_config_test.go
This pull request refactors platform-specific code by replacing string literals representing operating systems with existing predefined constants in the package that were used for VMware Tools. This change improves code maintainability, reduces the risk of typos, and centralizes OS references for easier updates.
**Platform detection refactoring:**
* Replaced string literals such as `"darwin"`, `"linux"`, and `"windows"` with constants (`osMacOS`, `osLinux`, `osWindows`) in the driver selection logic in `driver.go`, improving clarity and maintainability.
* Updated platform checks in guest IP detection and verification routines in `driver.go` to use the new OS constants. [[1]](diffhunk://#diff-f2729c057c901fdc3e94cc6999b57818480a13abecfb0fccb5b7a0fccfbf7be3L592-R592) …
> refactor: os checks

- builder/vmware/common/driver_parser.go
Aligns the `NetworkingConfig` receiver naming in the `builder/vmware/common/driver_parser.go` from `e` to `c` in two methods for better clarity and consistency.
Clarity and consistency
Revert commit.
None.
> refactor: align receiver variables

- builder/vmware/common/driver.go
- builder/vmware/iso/step_create_vmx.go
Improves resource management and log clarity in the codebase. The main changes include more robust file handling (especially with closing files after reading), better logging practices with explicit log levels, and a simplification in reading disk template files.
* Ensured that file handles for DHCP lease files are explicitly closed after reading, with warnings logged if closing fails, both for standard and Apple DHCP leases in `driver.go`. [[1]](diffhunk://#diff-f2729c057c901fdc3e94cc6999b57818480a13abecfb0fccb5b7a0fccfbf7be3L522-R531) [[2]](diffhunk://#diff-f2729c057c901fdc3e94cc6999b57818480a13abecfb0fccb5b7a0fccfbf7be3L604-R614)
* Updated log messages to include explicit log levels such as `[WARN]` and `[INFO]` for better clarity and consistency throughout DHCP lease handling logic in …
> refactor: Improve file handling and logging

- builder/vmware/common/driver.go
- builder/vmware/iso/builder_test.go
- builder/vmware/iso/config.go
Refactors how hardware version constants are managed for virtual machine creation, improving maintainability and consistency across the codebase. The minimum and default hardware version constants are moved to a shared location, and all references are updated accordingly.
* Added `MinimumHardwareVersion` and `DefaultHardwareVersion` constants to `builder/vmware/common/driver.go`, centralizing their definition for use across the project.
* Removed locally defined `minimumHardwareVersion` and `defaultHardwareVersion` constants from `builder/vmware/iso/config.go`, updating the code to use the shared constants from `vmwcommon`.
* Updated the logic in `builder/vmware/iso/config.go` to use `vmwcommon.DefaultHardwareVersion` and `vmwcommon.MinimumHardwareVersion` when preparing configuration, …
> refctor: move hardware version constants

- .web-docs/components/builder/vmx/README.md
- builder/vmware/common/step_configure_vmx.go
- builder/vmware/common/step_configure_vmx_test.go
- builder/vmware/vmx/builder.go
- builder/vmware/vmx/config.go
- builder/vmware/vmx/config.hcl2spec.go
- docs-partials/builder/vmware/vmx/Config-not-required.mdx
Fixes the issue attaching a custom CD when `cd_files` is used.
Closes #15
Closes #182
> fix: attach custom cd for `cd_files`

- builder/vmware/common/hw_config.go
- builder/vmware/common/hw_config_test.go
- builder/vmware/iso/builder_test.go
Adds a check to ensure 'network_adapter_type' is provided and is one of the allowed values. IN my prior change, only invalid values were checked; now missing value are also reported as error.
**Example w/o 'network_adapter_type' provided:**
```shell
packer-plugin-vmware/example on  main [!?] via 🐹 v1.25.0 took 6.1s 
✦ ➜ packer build -var-file=pkrvars/debian/fusion-13.pkrvars.hcl .
Error: 1 error(s) occurred:
* 'network_adapter_type' is required; must be one of vmxnet3, e1000e, e1000
on sources.pkr.hcl line 9:
(source code not available)
```
**Example w/ an invalid option for 'network_adapter_type' provided:**
```shell
packer-plugin-vmware/example on  main [!?] via 🐹 v1.25.0 
✦ ➜ packer build -var-file=pkrvars/debian/fusion-13.pkrvars.hcl .
Error: 1 error(s) occurred:
* invalid …
```
> refactor: update network adapter type validation

- .web-docs/components/builder/iso/README.md
- builder/vmware/common/driver.go
- builder/vmware/iso/config.go
- docs-partials/builder/vmware/iso/Config-not-required.mdx
Updated the minimum supported hardware version from 13 to 19 and the default from 19 to 21 in the `vmware-iso` builder.
Reference: https://knowledge.broadcom.com/external/article/315655/virtual-machine-hardware-versions.html
* Increased the minimum supported hardware version from 13 to 19 and the default hardware version from 19 to 21 in the `Config` struct documentation in `builder/vmware/iso/config.go`.
* Updated the constants `MinimumHardwareVersion` and `DefaultHardwareVersion` in `builder/vmware/common/driver.go` to match the new requirements.
Documentation consistency:
* Updated the hardware version information in `docs-partials/builder/vmware/iso/Config-not-required.mdx` for consistency with the code changes.
Ensure consistency and reflect supported versions in #369.
Revert commit. …
> chore: update virtual hardware versions

- .web-docs/components/builder/iso/README.md
- builder/vmware/common/driver.go
- builder/vmware/iso/config.go
- docs-partials/builder/vmware/iso/Config-not-required.mdx
Updates the default guest operating system identifier for virtual machines to be architecture-aware, improving compatibility and clarity for users on different platforms. The changes ensure that the default value for `guest_os_type` is set appropriately based on whether the runtime architecture is `amd64`, `arm64`, or something else, and updates documentation to reflect this behavior.
Guest OS Type Handling:
* Added architecture-specific constants for guest OS type: `DefaultGuestOsTypeAmd64` (`other-64`), `DefaultGuestOsTypeArm64` (`arm-other-64`), and a fallback value (`other`) in `builder/vmware/common/driver.go`.
* Updated logic in `builder/vmware/iso/config.go` so that if `guest_os_type` is not specified, it is set based on the runtime architecture, with a warning for unrecognized …
> refactor: default guest os type based on architecture

- go.mod
- go.sum
Updates `hashicorp/packer-plugin-sdk` from v0.6.2. to v0.6.3.
> chore(deps): bump hashicorp/packer-plugin-sdk from v0.6.2 to v0.6.3

- builder/vmware/common/step_vnc_boot_command.go
- builder/vmware/common/step_vnc_connect.go
- go.mod
- go.sum
Replaced the deprecated/archived `mitchellh/go-vnc` library with `tenthirtyam/go-vnc`. Updated method signatures and usage to match the new library's API for improved VNC connection handling.
Dependency Update:
* Replaced the `github.com/mitchellh/go-vnc` dependency with `github.com/tenthirtyam/go-vnc v1.0.0` in `go.mod` and all relevant imports. [[1]](diffhunk://#diff-e7d304c44ccc1f16646595ce0d8174875c322769b71a361ffda27440f4f285f1L17-R17) [[2]](diffhunk://#diff-3e7e9fecf2da616495990c6c91245d6affda62cb5e489e6248d1e5e7305a8e0fL13-R13) [[3]](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L10-R11)
Connection Improvements:
* Refactored the `ConnectVNC` method in `step_vnc_connect.go` to accept a `context.Context` parameter and use the new `ClientWithContext` …
> refactor(deps): switch vnc library to `tenthirtyam/go-vnc`
